[tool.poetry]
name = "tiendil_tensorboard_utilities"
version = "0.1"
description = "Custom installation."
authors = ["Aliaksei Yaletski (Tiendil) <a.eletsky@gmail.com>"]

[tool.poetry.dependencies]
python = "3.10"

tensorflow = "^2.9"
tensorboard-plugin-profile = "^2.8"